//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karizi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_A3C991_karizi2018Entities : DbContext
    {
        public DB_A3C991_karizi2018Entities()
            : base("name=DB_A3C991_karizi2018Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<AboutUsPhoto> AboutUsPhotoes { get; set; }
        public virtual DbSet<BottomblockPhoto> BottomblockPhotoes { get; set; }
        public virtual DbSet<BottomblockText> BottomblockTexts { get; set; }
        public virtual DbSet<MiddleBlockPhoto> MiddleBlockPhotoes { get; set; }
        public virtual DbSet<MiddleBlockText> MiddleBlockTexts { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Portfolio> Portfolios { get; set; }
        public virtual DbSet<PortfolioPhoto> PortfolioPhotoes { get; set; }
        public virtual DbSet<Production> Productions { get; set; }
        public virtual DbSet<ProductionPhoto> ProductionPhotoes { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServicesPhoto> ServicesPhotoes { get; set; }
        public virtual DbSet<SliderPhoto> SliderPhotoes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
    }
}
