//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karizi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductionPhoto
    {
        public int Id { get; set; }
        public int ProductionId { get; set; }
        public string Photo { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string PhotoTitle { get; set; }
    
        public virtual Production Production { get; set; }
    }
}
